server:
  port: 8080

spring:
  application:
    name: gateway

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka}

zuul:
  routes:
    microservice:
      path: /microservices/**
      serviceId: MICROSERVICE
      stripPrefix: false


